---
- name: fail2ban
  hosts: all
  become: yes 
  become_user: root

  tasks: 
    - name: Install fail2ban on Debian System
      apt: name=fail2ban update_cache=yes state=latest
  # vars:
  #   # Fail2Ban vars
  #   # bantime is defined in minutes
  #   bantime: 3600
  #   destemail: "tarequensu@gmail.com"
  #   hook_url: "https://hooks.slack.com/services/id/id/id"
    - name: Copy fail2ban.local to /etc/fail2ban/
      template:
            src: templates/fail2ban.local
            dest: /etc/fail2ban/
            mode: 0644
            owner: root
            group: root
            

    - name: Copy jail.local to /etc/fail2ban/
      template:
            src: templates/jail.local
            dest: /etc/fail2ban/
            mode: 0644
            owner: root
            group: root
    - name: fail2ban restarting ...
      systemd:
        daemon_reload: yes
        enabled: yes
        state: restarted
        name: fail2ban.service
            
  
  
  # handlers:
  #   - name: restart fail2ban
  #     service: name=fail2ban state=restarted 
      

# - name: Copy slack_notify.sh.j2 to /etc/fail2ban/slack_notify.sh
#   template:
#     src: slack_notify.sh.j2
#     dest: /etc/fail2ban/slack_notify.sh
#     mode: 0755
#     owner: root
#     group: root
#   notify:
#     - restart fail2ban
# - name: Copy iptables-multiport.conf.j2 to /etc/fail2ban/action.d/iptables-multiport.conf
#   template:
#     src: iptables-multiport.conf.j2
#     dest: /etc/fail2ban/action.d/iptables-multiport.conf
#     mode: 0644
#     owner: root
#     group: root
#   notify:
#     - restart fail2ban

# - name: Copy nginx-generic.conf.j2 to /etc/fail2ban/filter.d/nginx-generic.conf
#   template:
#     src: nginx-generic.conf.j2
#     dest: /etc/fail2ban/filter.d/nginx-generic.conf
#     mode: 0644
#     owner: root
#     group: root
#   notify:
#     - restart fail2ban

# - name: Copy nginx-wordpress.conf.j2 to /etc/fail2ban/filter.d/nginx-wordpress.conf
#   template:
#     src: nginx-wordpress.conf.j2
#     dest: /etc/fail2ban/filter.d/nginx-wordpress.conf
#     mode: 0644
#     owner: root
#     group: root
#   notify:
#     - restart fail2ban

# - name: Copy slack.conf.j2 to /etc/fail2ban/action.d/slack.conf
#   template:
#     src: slack.conf.j2
#     dest: /etc/fail2ban/action.d/slack.conf
#     mode: 0644
#     owner: root
#     group: root
#   notify:
#     - restart fail2ban

  