- hosts: all
  become: yes 
  
   
  tasks:
  - name : Install Python Package
    apt: name=python3 update_cache=yes state=latest
 
  - name : Install Let's Encrypt Package
    apt: name=python3-certbot-apache update_cache=yes state=latest
 
  - name: Create and Install Cert Using Certbot Plugin
    command: "certbot --apache -d example.com -m tarequensu@gmail.com --agree-tos --noninteractive --redirect"
 
   
  - name: Set Letsencrypt Cronjob for Certificate Auto Renewal
    cron: name=letsencrypt_renewal special_time=monthly job="/usr/bin/certbot renew"
    when: ansible_facts['os_family'] == "Debian"