---
- name: Configuring System Firewall using ufw
  hosts: all
  become: yes
  
  
    
  tasks:
    - name: Install UFW firewall
      apt: name=ufw update_cache=yes state=latest  
  
    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Allow OpenSSH
      community.general.ufw:
        rule: allow
        name: OpenSSH
    

    - name: Open firewall http
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Open firewall for https
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Open firewall for Docker Container 8080 
      community.general.ufw:
        rule: allow
        port: 8080
        proto: tcp
    
    - name: Open firewall for node_exporter 9100
      community.general.ufw:
        rule: allow
        port: 9100
        proto: tcp
